const termsSections = [
  {
    title: "Introduction",
    content: `These Terms of Service ("Terms") govern your access to and use of the ReRoom website (https://reroom.ai) (the "Service"), owned and operated by Stylefie, Inc. ("us", "we", or "our"). By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the Terms, then you may not access the Service.`,
  },
  {
    title: "Account Registration",
    content: `To access some features of the Service, you may be required to create an account. You must provide accurate and complete information and update it promptly. You are responsible for maintaining the confidentiality of your password and all activities under your account.

You agree not to share your account or allow others to access it. Notify us immediately of any unauthorized use. We may terminate accounts if used in violation of these Terms.`,
  },
  {
    title: "Use of the Service",
    content: `You agree to use the Service in accordance with the law and these Terms. You may not damage, disable, or impair the Service or interfere with others' use. Unauthorized access attempts through hacking or other means are strictly prohibited.`,
  },
  {
    title: "No Refunds",
    content: `All purchases made on or through the Service are final and non-refundable.`,
  },
  {
    title: "Commercial Usage",
    content: `Images generated by the AI on the Service can be used for commercial purposes without any additional fees or royalties.`,
  },
  {
    title: "Intellectual Property",
    content: `The Service and its technology are the exclusive property of Stylefie, Inc. You retain ownership of your input and generated output, but Stylefie, Inc. does not claim ownership of it. However, similar output may be generated for others.

Do not copy, modify, or distribute the underlying technology. Output use is subject to these Terms.`,
  },
  {
    title: "User-Generated Content",
    content: `By using the Service, you grant Stylefie, Inc. rights to use your generated content for marketing and other purposes. You represent that you have the rights to the content you provide.`,
  },
  {
    title: "Termination",
    content: `We may suspend or terminate your account without notice if you breach these Terms. You may stop using the Service at any time.`,
  },
  {
    title: "Disclaimer",
    content: `The Service is provided "AS IS" and "AS AVAILABLE" without warranties. We do not guarantee that the Service will be error-free or secure.`,
  },
  {
    title: "Limitation of Liability",
    content: `Stylefie, Inc. is not liable for any indirect or consequential damages arising from your use of the Service.`,
  },
  {
    title: "Indemnification",
    content: `You agree to defend and indemnify Stylefie, Inc. against any claims arising from your use of the Service or violation of these Terms.`,
  },
  {
    title: "Governing Law and Jurisdiction",
    content: `These Terms are governed by the laws of the jurisdiction where Stylefie, Inc. is incorporated. Disputes will be resolved in that jurisdiction's courts.`,
  },
  {
    title: "Changes to the Terms",
    content: `We may modify these Terms at any time. Continued use of the Service after changes means you accept the revised Terms.`,
  },
  {
    title: "Data Breach and Cloud Vendor Liability",
    content: `We use third-party cloud vendors for storage. While we take precautions, we are not liable for breaches caused by these vendors. Liability is governed by agreements with those vendors.`,
  },
  {
    title: "Contact Us",
    content: `If you have any questions about these Terms, contact us at feedback@reroom.ai.`,
  },
];

export default function page() {
  return (
    <div className="mx-auto mt-20 w-[60vw] p-6 text-gray-800">
      <h1 className="mb-4 text-3xl font-bold">Terms of Service</h1>
      <p className="mb-8 text-sm text-gray-500">Last updated: April 22, 2023</p>

      {termsSections.map((section, index) => (
        <div key={index} className="mb-6">
          <h2 className="mb-2 mt-12 text-xl font-semibold">{section.title}</h2>
          <p className="whitespace-pre-line">{section.content}</p>
        </div>
      ))}
    </div>
  );
}
